namespace KowhaiSymbols
{
    public static class Symbols
    {
        public static string[] Strings =
        {
            "Settings",
            "Shadow",
            "Actions",
            "Scope",
            "UnsolicitedEvent",
            "Start",
            "Stop",
            "Status",
            "Beep",
            "Big",
            "Fail",
            "UnsolicitedMode",
            "FluxCapacitor",
            "Frequency",
            "Coefficient",
            "Gain",
            "Oven",
            "Temp",
            "Timeout",
            "Union",
            "Owner",
            "Duration",
            "Pixels",
            "Running",
            "Delay",
            "Time",
        };
        public enum Constants
        {
            Settings,
            Shadow,
            Actions,
            Scope,
            UnsolicitedEvent,
            Start,
            Stop,
            Status,
            Beep,
            Big,
            Fail,
            UnsolicitedMode,
            FluxCapacitor,
            Frequency,
            Coefficient,
            Gain,
            Oven,
            Temp,
            Timeout,
            Union,
            Owner,
            Duration,
            Pixels,
            Running,
            Delay,
            Time,
        };
    }
}
