#!/usr/bin/env python

import ctypes

from kowhai import *

# protocol commands 
KOW_CMD_GET_VERSION = 0x00
KOW_CMD_GET_VERSION_ACK = 0x0F
KOW_CMD_GET_TREE_LIST = 0x10
KOW_CMD_GET_TREE_LIST_ACK = 0x1F
KOW_CMD_GET_TREE_LIST_ACK_END = 0x1E
KOW_CMD_WRITE_DATA = 0x20
KOW_CMD_WRITE_DATA_ACK = 0x2F
KOW_CMD_READ_DATA = 0x30
KOW_CMD_READ_DATA_ACK = 0x3F
KOW_CMD_READ_DATA_ACK_END = 0x3E
KOW_CMD_READ_DESCRIPTOR = 0x40
KOW_CMD_READ_DESCRIPTOR_ACK = 0x4F
KOW_CMD_READ_DESCRIPTOR_ACK_END = 0x4E
KOW_CMD_GET_FUNCTION_LIST = 0x50
KOW_CMD_GET_FUNCTION_LIST_ACK = 0x5F
KOW_CMD_GET_FUNCTION_LIST_ACK_END = 0x5E
KOW_CMD_GET_FUNCTION_DETAILS = 0x60
KOW_CMD_GET_FUNCTION_DETAILS_ACK = 0x6F
KOW_CMD_CALL_FUNCTION = 0x70
KOW_CMD_CALL_FUNCTION_ACK = 0x7F
KOW_CMD_CALL_FUNCTION_RESULT = 0x7E
KOW_CMD_CALL_FUNCTION_RESULT_END = 0x7D
KOW_CMD_CALL_FUNCTION_FAILED = 0x7C
KOW_CMD_GET_SYMBOL_LIST = 0x80
KOW_CMD_GET_SYMBOL_LIST_ACK = 0x8F
KOW_CMD_GET_SYMBOL_LIST_ACK_END = 0x8E

# protocol error codes
KOW_CMD_ERROR_INVALID_COMMAND = 0xF0
KOW_CMD_ERROR_INVALID_TREE_ID = 0xF1
KOW_CMD_ERROR_INVALID_FUNCTION_ID = 0xF2
KOW_CMD_ERROR_INVALID_SYMBOL_PATH = 0xF3
KOW_CMD_ERROR_INVALID_PAYLOAD_OFFSET = 0xF4
KOW_CMD_ERROR_INVALID_PAYLOAD_SIZE = 0xF5
KOW_CMD_ERROR_UNKNOWN = 0xFF

if __name__ == "__main__":
    print 'yoyo'
    print kowhai_lib
